apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/vote-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongoadmin:secret@mongo:27017"

