apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: voting-app
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==       # base64 of 'mongoadmin'
  mongo-root-password: c2VjcmV0              # base64 of 'secret'

